# Generated by Django 3.2.8 on 2021-11-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmt_mood_translator', '0002_alter_input_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='positivity',
            field=models.CharField(max_length=500),
        ),
    ]
